# Generated by Django 3.0.2 on 2020-01-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historian', '0003_pricepoint_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricepoint',
            name='coin',
            field=models.CharField(default='No default should be saved', max_length=5),
        ),
    ]
